version: '3.8'
services:
  redis:
    image: 'bitnami/redis:latest'
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=my_redis_password
    networks: 
      - medical-system-network
networks: 
  medical-system-network:
    external: true