version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - KAFKA_BROKERS=kafka-host:9091,kafka-host:9092
      - DB_HOST=mongodb
    networks:
      - medical-system-network
    logging:
        driver: json-file
        options:
            max-size: 10m
            max-file: 10
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
networks:
  medical-system-network:
    external: true